# Generated by Django 4.2.7 on 2025-11-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='action_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conversation',
            name='decisions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conversation',
            name='key_points',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
